"""modify answer and question tables

Revision ID: 0ee7a876ffa2
Revises: a2ad522fdde8
Create Date: 2020-06-23 16:32:59.848212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee7a876ffa2'
down_revision = 'a2ad522fdde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__answer__question__4F7CD00D', 'answer', type_='foreignkey')
    op.drop_column('answer', 'question_id')
    op.add_column('question', sa.Column('answer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'answer', ['answer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'answer_id')
    op.add_column('answer', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('FK__answer__question__4F7CD00D', 'answer', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
