"""add new score field to user

Revision ID: 193bcad68064
Revises: 296618e1138c
Create Date: 2020-07-13 16:30:07.090571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193bcad68064'
down_revision = '296618e1138c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'score')
    # ### end Alembic commands ###
