"""remove fifth option in question

Revision ID: 296618e1138c
Revises: 186ec51581de
Create Date: 2020-07-03 09:23:59.877858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296618e1138c'
down_revision = '186ec51581de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'option_five')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('option_five', sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
