"""modify module name

Revision ID: a2ad522fdde8
Revises: b9ad2718266b
Create Date: 2020-06-20 20:51:53.504126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ad522fdde8'
down_revision = 'b9ad2718266b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_module_name', table_name='module')
    op.create_index(op.f('ix_module_name'), 'module', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_name'), table_name='module')
    op.create_index('ix_module_name', 'module', ['name'], unique=False)
    # ### end Alembic commands ###
