"""question and answer table

Revision ID: b409c35871a9
Revises: 2066973dd55a
Create Date: 2020-05-28 15:24:58.285354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b409c35871a9'
down_revision = '2066973dd55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('question', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_module'), 'question', ['module'], unique=False)
    op.create_index(op.f('ix_question_timestamp'), 'question', ['timestamp'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_one', sa.String(length=64), nullable=True),
    sa.Column('option_two', sa.String(length=64), nullable=True),
    sa.Column('option_three', sa.String(length=64), nullable=True),
    sa.Column('option_four', sa.String(length=64), nullable=True),
    sa.Column('option_five', sa.String(length=64), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_timestamp'), table_name='question')
    op.drop_index(op.f('ix_question_module'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
