"""module table

Revision ID: b9ad2718266b
Revises: bfe6d383e6d0
Create Date: 2020-06-19 22:32:00.242346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ad2718266b'
down_revision = 'bfe6d383e6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_name'), 'module', ['name'], unique=False)
    op.add_column('question', sa.Column('module_id', sa.Integer(), nullable=True))
    op.drop_index('ix_question_module', table_name='question')
    op.create_foreign_key(None, 'question', 'module', ['module_id'], ['id'])
    op.drop_column('question', 'module')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('module', sa.VARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_index('ix_question_module', 'question', ['module'], unique=False)
    op.drop_column('question', 'module_id')
    op.drop_index(op.f('ix_module_name'), table_name='module')
    op.drop_table('module')
    # ### end Alembic commands ###
