"""add tutor field to user table

Revision ID: bfe6d383e6d0
Revises: 1c6a16a4a437
Create Date: 2020-06-17 22:07:25.244713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe6d383e6d0'
down_revision = '1c6a16a4a437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tutor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tutor')
    # ### end Alembic commands ###
